# Generated by Django 5.2.5 on 2025-08-21 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryrewriting', '0003_alter_dailysummary_user_alter_diaryentry_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary_text', models.TextField(blank=True)),
                ('emotion', models.CharField(blank=True, max_length=50)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['user', 'date'], name='diaryrewrit_user_id_2a046a_idx'),
        ),
        migrations.AddField(
            model_name='summaryhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='summaryhistory',
            index=models.Index(fields=['user', 'date', '-created_at'], name='diaryrewrit_user_id_76dada_idx'),
        ),
    ]
