global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:8001"  # macOS/Windows
          # Linux일 경우: "172.17.0.1:8001" 또는 호스트 IP 사용

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers: []  # 나중에 Alertmanager 추가 시 설정
